configMapGenerator:
  - name: keystone
    files:
      - conf/keystone.conf
secretGenerator:
  - name: fernet-keys
    # NOTE: Secret keys cannot be digits,so prefix them with letter
    literals:
      - k0=2Rlc-npWYOGqqG1zM-bmfBj2apLacLXhIbBsdyqQ0zg=
      - k1=sQyQVikArus5DRomTHCLPEIJO2yYkeB5nDdaasIKHVQ=
    type: generic
resources:
  - deployment.yaml
  - db.yaml
  - service.yaml
  - ingress.yaml
