[package]
name = "openstack_keystone"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Artem Goncharov (gtema)"]
rust-version = "1.83"  # MSRV
repository = "https://github.com/gtema/keystone"

[[bin]]
name="keystone"
path="src/bin/keystone.rs"

[dependencies]
async-trait = { version = "^0.1" }
axum = { version = "^0.8", features = ["macros"] }
bcrypt = { version = "0.17", features = ["alloc"] }
bytes = { version = "^1.10" }
chrono = { version = "^0.4" }
clap = { version = "^4.5", features = ["derive"] }
color-eyre = { version = "^0.6" }
config = { version = "^0.15", features = ["ini"] }
derive_builder = { version = "^0.20" }
dyn-clone = "1.0.18"
eyre = { version = "^0.6" }
#mockall_double = { version = "^0.3" } # Used for testing but need to be in main requirements
pbkdf2 = { version = "^0.12", features = ["password-hash"] }
pwhash = "1.0.0"
regex = "1.11.1"
sea-orm = { version = "^1.1", features = ["sqlx-mysql", "sqlx-postgres", "runtime-tokio"] }
serde = { version = "^1.0" }
serde_json = { version = "^1.0" }
thiserror = { version = "^2.0" }
tokio = { version = "^1.43", features = ["macros", "signal", "rt-multi-thread"] }
tower = { version = "^0.5" }
tower-http = { version = "^0.6", features = ["compression-full", "request-id", "sensitive-headers", "trace", "util"] }
tracing = { version = "^0.1" }
tracing-subscriber = { version = "^0.3" }
utoipa = { version = "^5.3", features = ["axum_extras", "chrono"] }
utoipa-axum = { version = "^0.2" }
utoipa-swagger-ui = { version = "^9.0", features = ["axum", "vendored"], default-features = false }
uuid = { version = "^1.13", features = ["v4"] }

[dev-dependencies]
http-body-util = "^0.1"
# mockall = "^0.13"
sea-orm = { version = "*", features = ["mock"]}
