[package]
name = "openstack_keystone"
version = "0.1.0"
edition = "2021"

[[bin]]
name="keystone"
path="src/bin/keystone.rs"

[dependencies]
async-trait = { version = "^0.1" }
axum = { version = "^0.8", features = ["macros"] }
chrono = { version = "^0.4" }
clap = { version = "^4.5", features = ["derive"] }
config = { version = "^0.15", features = ["ini"] }
derive_builder = { version = "^0.20" }
sea-orm = { version = "^1.1", features = ["sqlx-mysql", "sqlx-postgres", "runtime-tokio"] }
serde = { version = "^1.0" }
serde_json = { version = "^1.0" }
thiserror = { version = "^2.0" }
tokio = { version = "^1.43", features = ["macros", "signal", "rt-multi-thread"] }
tower = { version = "^0.5" }
tower-http = { version = "^0.6", features = ["trace"] }
tracing = { version = "^0.1" }
tracing-subscriber = { version = "^0.3" }
utoipa = { version = "^5.3", features = ["axum_extras", "chrono"] }
utoipa-axum = { version = "^0.2" }
utoipa-swagger-ui = { version = "^9.0", features = ["axum", "vendored"], default-features = false }

[dev-dependencies]
sea-orm = { version = "*", features = ["mock"]}
