[package]
name = "keystone"
version = "0.1.0"
edition = "2024"

[[bin]]
name="testy"
path="src/bin/testy.rs"

[dependencies]
async-trait = "0.1.85"
axum = {version = "^0.8"}
config = {version = "^0.15", features = ["ini"]}
openstack_sdk = {version = "^0.9", default-features=false, features = ["identity", "async"]}
sea-orm = {version = "^1.1", features=["sqlx-mysql", "runtime-tokio", "debug-print"]}
serde = {version="^1.0"}
tokio = "1.43.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
utoipa = {version="^5.3", features = ["axum_extras"]}
utoipa-axum = {version="^0.2"}
utoipa-swagger-ui = {version = "9.0.0", features = ["axum", "vendored"], default-features = false}

