//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::Type;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "assignment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub r#type: Type,
    #[sea_orm(primary_key, auto_increment = false)]
    pub actor_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub inherited: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
