//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "federated_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: String,
    pub idp_id: String,
    pub protocol_id: String,
    pub unique_id: String,
    pub display_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::federation_protocol::Entity",
        from = "(Column::ProtocolId, Column::IdpId)",
        to = "(super::federation_protocol::Column::Id, super::federation_protocol::Column::IdpId)",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    FederationProtocol,
    #[sea_orm(
        belongs_to = "super::identity_provider::Entity",
        from = "Column::IdpId",
        to = "super::identity_provider::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    IdentityProvider,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::federation_protocol::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederationProtocol.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::identity_provider::Entity> for Entity {
    fn to() -> RelationDef {
        super::federation_protocol::Relation::IdentityProvider.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::federation_protocol::Relation::FederatedUser
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
