//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "federation_protocol")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub idp_id: String,
    pub mapping_id: String,
    pub remote_id_attribute: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::federated_user::Entity")]
    FederatedUser,
    #[sea_orm(
        belongs_to = "super::identity_provider::Entity",
        from = "Column::IdpId",
        to = "super::identity_provider::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    IdentityProvider,
}

impl Related<super::federated_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedUser.def()
    }
}

impl Related<super::identity_provider::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityProvider.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
