//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "identity_provider")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub enabled: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub domain_id: String,
    pub authorization_ttl: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::expiring_user_group_membership::Entity")]
    ExpiringUserGroupMembership,
    #[sea_orm(has_many = "super::federated_user::Entity")]
    FederatedUser,
    #[sea_orm(has_many = "super::federation_protocol::Entity")]
    FederationProtocol,
    #[sea_orm(has_many = "super::idp_remote_ids::Entity")]
    IdpRemoteIds,
}

impl Related<super::expiring_user_group_membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpiringUserGroupMembership.def()
    }
}

impl Related<super::federation_protocol::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederationProtocol.def()
    }
}

impl Related<super::idp_remote_ids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdpRemoteIds.def()
    }
}

impl Related<super::federated_user::Entity> for Entity {
    fn to() -> RelationDef {
        super::federation_protocol::Relation::FederatedUser.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::federation_protocol::Relation::IdentityProvider
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
