//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "implied_role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub prior_role_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub implied_role_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::ImpliedRoleId",
        to = "super::role::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Role2,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::PriorRoleId",
        to = "super::role::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    Role1,
}

impl ActiveModelBehavior for ActiveModel {}
