//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "password")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub local_user_id: i32,
    pub expires_at: Option<DateTime>,
    pub self_service: i8,
    pub password_hash: Option<String>,
    pub created_at_int: i64,
    pub expires_at_int: Option<i64>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::local_user::Entity",
        from = "Column::LocalUserId",
        to = "super::local_user::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    LocalUser,
}

impl Related<super::local_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocalUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
