//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project_endpoint_group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub endpoint_group_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub project_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::endpoint_group::Entity",
        from = "Column::EndpointGroupId",
        to = "super::endpoint_group::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    EndpointGroup,
}

impl Related<super::endpoint_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EndpointGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
