//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub extra: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub enabled: Option<i8>,
    pub domain_id: String,
    pub parent_id: Option<String>,
    pub is_domain: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::DomainId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    SelfRef1,
    #[sea_orm(has_many = "super::project_option::Entity")]
    ProjectOption,
    #[sea_orm(has_many = "super::project_tag::Entity")]
    ProjectTag,
}

impl Related<super::project_option::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectOption.def()
    }
}

impl Related<super::project_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
