//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "registered_limit")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: String,
    pub service_id: Option<String>,
    pub region_id: Option<String>,
    pub resource_name: Option<String>,
    pub default_limit: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(primary_key)]
    pub internal_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
