//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub extra: Option<String>,
    pub domain_id: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::role_option::Entity")]
    RoleOption,
}

impl Related<super::role_option::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RoleOption.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
