//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "service_provider")]
pub struct Model {
    pub auth_url: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub enabled: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub sp_url: String,
    pub relay_state_prefix: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
