//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "trust")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub trustor_user_id: String,
    pub trustee_user_id: String,
    pub project_id: Option<String>,
    pub impersonation: i8,
    pub deleted_at: Option<DateTime>,
    pub expires_at: Option<DateTime>,
    pub remaining_uses: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extra: Option<String>,
    pub expires_at_int: Option<i64>,
    pub redelegated_trust_id: Option<String>,
    pub redelegation_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
