[package]
name = "load_test"
version = "0.1.0"
rust-version = "1.85"  # MSRV
edition = "2024"

[dependencies]
goose = { version = "^0.18" }
tokio = { version = "^1.44" }
openstack_sdk = { version = "^0.22", default-features = false, features = ["async", "identity"] }
