name: Benchmarks

permissions:
  contents: read

on:
  push:
    branches: "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  bench_main:
    permissions:
      checks: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8

      - uses: bencherdev/bencher@main

      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project keystone \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ${{ matrix.os }} \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --adapter rust_criterion \
          cargo bench
