name: Benchmarks

permissions:
  contents: read

on:
  push:
    branches: "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  bench_main:
    permissions:
      checks: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0

      - uses: bencherdev/bencher@main

      - name: Track base branch benchmarks with Bencher
        run: |
          bencher run \
          --project keystone \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ${{ matrix.os }} \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --adapter rust_criterion \
          cargo bench
