name: Integration

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Integration
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: keystone
          POSTGRES_PASSWORD: '1234'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install necessary python packages
        run: pip install keystone uwsgi psycopg2

      - name: Prepare keystone config file
        env:
          store_id: ${{ steps.store.outputs.store_id }}
          model_id: ${{ steps.store.outputs.model_id }}
        run: |
          mkdir -p etc
          echo "[database]" >> etc/keystone.conf
          echo "connection = postgresql://keystone:1234@127.0.0.1:5432/keystone" >> etc/keystone.conf
          echo "[fernet_receipts]" >> etc/keystone.conf
          echo "key_repository = $(pwd)/etc/fernet" >> etc/keystone.conf
          echo "[fernet_tokens]" >> etc/keystone.conf
          echo "key_repository = $(pwd)/etc/fernet" >> etc/keystone.conf
          cat etc/keystone.conf

      - name: Init keystone
        run: |
          mkdir -p etc/fernet
          keystone-manage --config-file etc/keystone.conf db_sync
          keystone-manage --config-file etc/keystone.conf fernet_setup
          keystone-manage --config-file etc/keystone.conf bootstrap --bootstrap-password password
